/**
 * mockIncomeTaxPortal.js
 * ─────────────────────────────────────────────────────────────────────────────
 * Income Tax Department Portal Simulation
 * (Form 26AS + ITR Cross-Reference for Salary Truth Verification)
 *
 * WHY INCOME TAX DATA IS A POWERFUL SALARY TRUTH SIGNAL:
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * 1. FORM 26AS (Annual Tax Credit Statement):
 *    → Automatically generated by IT Department
 *    → Employer files TDS returns (Form 24Q) each quarter
 *    → Shows EXACTLY how much TDS employer deducted and deposited on your behalf
 *    → Employee has ZERO control over this document
 *    → Key: TDS amount on Form 26AS → reverse-calculate approximate salary
 *
 * 2. ITR (Income Tax Return):
 *    → Filed by employee annually
 *    → Declared salary in ITR vs salary slip claim
 *    → If ITR declares ₹12L salary but slip claims ₹7L → caught!
 *
 * 3. FORM 16 (TDS Certificate from Employer):
 *    → Issued by employer every year
 *    → Contains TAN (Tax Deduction Account Number) of employer
 *    → TAN can be verified against IT Department records
 *
 * Real Production:
 *    e-Filing Portal: https://www.incometax.gov.in/iec/foportal/
 *    TRACES Portal (TDS): https://www.tdscpc.gov.in/
 *    Authorized agencies can access via API with user PAN + OTP consent.
 * ─────────────────────────────────────────────────────────────────────────────
 */

// ─────────────────────────────────────────────────────────────────────────────
// TDS Slab Calculation (FY 2025-26 — New Tax Regime Default)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * calculateExpectedTDS(annualSalary)
 * Calculates expected annual TDS based on Income Tax slabs.
 *
 * FY 2025-26 New Tax Regime Slabs:
 *   Up to ₹3L        → 0%
 *   ₹3L – ₹7L        → 5%
 *   ₹7L – ₹10L       → 10%
 *   ₹10L – ₹12L      → 15%
 *   ₹12L – ₹15L      → 20%
 *   Above ₹15L       → 30%
 *
 * Standard Deduction: ₹75,000 (FY 2025-26)
 */
function calculateExpectedTDS(annualSalary) {
  const STANDARD_DEDUCTION = 75000;
  const taxableIncome = Math.max(0, annualSalary - STANDARD_DEDUCTION);

  let tax = 0;
  const breakdown = [];

  if (taxableIncome > 300000) {
    const slab1 = Math.min(taxableIncome - 300000, 400000); // 3L-7L @ 5%
    const t1 = slab1 * 0.05;
    tax += t1;
    if (t1 > 0) breakdown.push({ slab: "₹3L–₹7L", rate: "5%", amount: t1 });
  }
  if (taxableIncome > 700000) {
    const slab2 = Math.min(taxableIncome - 700000, 300000); // 7L-10L @ 10%
    const t2 = slab2 * 0.10;
    tax += t2;
    if (t2 > 0) breakdown.push({ slab: "₹7L–₹10L", rate: "10%", amount: t2 });
  }
  if (taxableIncome > 1000000) {
    const slab3 = Math.min(taxableIncome - 1000000, 200000); // 10L-12L @ 15%
    const t3 = slab3 * 0.15;
    tax += t3;
    if (t3 > 0) breakdown.push({ slab: "₹10L–₹12L", rate: "15%", amount: t3 });
  }
  if (taxableIncome > 1200000) {
    const slab4 = Math.min(taxableIncome - 1200000, 300000); // 12L-15L @ 20%
    const t4 = slab4 * 0.20;
    tax += t4;
    if (t4 > 0) breakdown.push({ slab: "₹12L–₹15L", rate: "20%", amount: t4 });
  }
  if (taxableIncome > 1500000) {
    const slab5 = (taxableIncome - 1500000) * 0.30; // Above 15L @ 30%
    tax += slab5;
    breakdown.push({ slab: "Above ₹15L", rate: "30%", amount: slab5 });
  }

  // Add 4% Health & Education cess
  const cess = tax * 0.04;
  const totalTax = Math.round(tax + cess);
  const monthlyTDS = Math.round(totalTax / 12);

  return {
    gross_annual: annualSalary,
    standard_deduction: STANDARD_DEDUCTION,
    taxable_income: taxableIncome,
    annual_tax: totalTax,
    monthly_tds: monthlyTDS,
    tax_breakdown: breakdown,
    tax_regime: "New Tax Regime (FY 2025-26)",
    zero_tax: totalTax === 0
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Seeded Random
// ─────────────────────────────────────────────────────────────────────────────
function seededRand(seed) {
  let s = 0;
  for (let i = 0; i < seed.length; i++) {
    s = Math.imul(31, s) + seed.charCodeAt(i) | 0;
  }
  return Math.abs(s);
}

// ─────────────────────────────────────────────────────────────────────────────
// Form 26AS Mock
// ─────────────────────────────────────────────────────────────────────────────

/**
 * fetchForm26AS(pan, financialYear)
 * ─────────────────────────────────────────────────────────────────────────────
 * Returns Form 26AS data for a given PAN.
 *
 * Form 26AS is generated AUTOMATICALLY by IT Dept from TDS filings.
 * Employer deposits TDS → IT Dept records it against employee's PAN.
 * Employee CANNOT modify this.
 *
 * @param {string} pan           - Employee's PAN number (e.g. AAPFU0939F)
 * @param {string} financialYear - e.g. "2025-2026"
 */
function fetchForm26AS(pan, financialYear) {
  if (!pan || !/^[A-Z]{5}[0-9]{4}[A-Z]$/.test(pan.toUpperCase())) {
    return {
      found: false,
      source: "Form 26AS — TRACES Portal",
      error: "Invalid PAN format. Cannot fetch Form 26AS.",
      flag: "INVALID_PAN_FOR_26AS"
    };
  }

  const hash = seededRand(pan.toUpperCase() + (financialYear || "2025-2026"));

  // 90% chance ITR/26AS data found (most salaried people have it)
  if (hash % 100 >= 90) {
    return {
      found: false,
      source: "Form 26AS — TRACES Portal",
      pan: pan.toUpperCase(),
      financial_year: financialYear,
      note: "No TDS credit found for this PAN in the given financial year. Possible: first job, very low income, or PAN mismatch.",
      flag: "NO_26AS_RECORD"
    };
  }

  // Deterministic salary-based TDS record
  const salaryBrackets = [180000, 240000, 300000, 420000, 600000, 840000,
    1000000, 1200000, 1500000, 2000000];
  const actualAnnualSalary = salaryBrackets[hash % salaryBrackets.length];
  const tdsCalc = calculateExpectedTDS(actualAnnualSalary);

  // Employer TAN (seeded)
  const employerTAN = `MUMP${String(hash % 99999).padStart(5, "0")}D`;

  // Quarterly TDS deposition (employer files each quarter)
  const quarters = ["Q1 (Apr-Jun 2025)", "Q2 (Jul-Sep 2025)", "Q3 (Oct-Dec 2025)", "Q4 (Jan-Mar 2026)"];
  const quarterlyTDS = Math.round(tdsCalc.annual_tax / 4);

  return {
    found: true,
    source: "Form 26AS — TRACES Portal (Immutable Govt Record)",
    pan: pan.toUpperCase(),
    financial_year: financialYear || "2025-2026",
    // THE KEY SALARY TRUTH SIGNAL:
    tds_records: [{
      employer_tan: employerTAN,
      section: "192 — Salary",           // Section 192 = TDS on Salary
      it_derived_annual_salary: actualAnnualSalary,  // What IT Dept knows about your salary
      annual_tds_deducted: tdsCalc.annual_tax,
      monthly_tds: tdsCalc.monthly_tds,
      quarterly_deposits: quarters.map((q, i) => ({
        quarter: q,
        tds_deposited: quarterlyTDS + (i === 3 ? tdsCalc.annual_tax % 4 : 0),
        status: "DEPOSITED"
      }))
    }],
    total_tds_for_year: tdsCalc.annual_tax,
    note: "TDS deposited by employer under Section 192 of Income Tax Act. Cannot be altered by employee."
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// ITR (Income Tax Return) Mock
// ─────────────────────────────────────────────────────────────────────────────

/**
 * fetchITRDetails(pan, financialYear)
 * Returns ITR filing details for a PAN.
 *
 * Key: If employee filed ITR declaring salary = ₹12L,
 * but uploads salary slip showing ₹7.5L → caught!
 */
function fetchITRDetails(pan, financialYear) {
  if (!pan || !/^[A-Z]{5}[0-9]{4}[A-Z]$/.test(pan.toUpperCase())) {
    return { found: false, error: "Invalid PAN" };
  }

  const hash = seededRand(pan.toUpperCase() + "ITR" + (financialYear || "2025-2026"));

  // 75% chance ITR filed
  if (hash % 100 >= 75) {
    return {
      found: false,
      source: "ITR — e-Filing Portal",
      pan: pan.toUpperCase(),
      itr_filed: false,
      note: "No ITR found for this PAN and FY. Possible: very low income, not required to file, or first year."
    };
  }

  const salaryBrackets = [200000, 300000, 480000, 650000, 900000,
    1100000, 1400000, 1800000, 2500000];
  const declaredSalary = salaryBrackets[hash % salaryBrackets.length];
  const itrForms = ["ITR-1 (Sahaj)", "ITR-1 (Sahaj)", "ITR-1 (Sahaj)", "ITR-2", "ITR-2"];

  return {
    found: true,
    source: "ITR — e-Filing Portal (Immutable Govt Record)",
    pan: pan.toUpperCase(),
    financial_year: financialYear || "2025-2026",
    itr_filed: true,
    itr_form: itrForms[hash % itrForms.length],
    acknowledgement_number: `AA${hash % 999999999}`,
    filing_date: `${10 + (hash % 20)}/07/2025`,
    // KEY SALARY TRUTH SIGNAL:
    declared_salary_income: declaredSalary,
    declared_gross_total_income: declaredSalary + (hash % 50000),
    refund_claimed: hash % 3 === 0,
    tax_paid: calculateExpectedTDS(declaredSalary).annual_tax,
    note: "ITR declared salary income. Employee signed this declaration under penalty of law."
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// TAN Verification (Employer TDS Registration)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * verifyEmployerTAN(tan, employerName)
 * TAN = Tax Deduction Account Number (10-digit, e.g. MUMP12345D)
 * Every employer that deducts TDS must have a TAN.
 * If Form 16 shows a TAN, we verify it's registered to this employer.
 */
function verifyEmployerTAN(tan, employerName) {
  if (!tan) return { valid: false, reason: "TAN not provided" };

  const tanRegex = /^[A-Z]{4}[0-9]{5}[A-Z]$/;
  if (!tanRegex.test(tan.toUpperCase())) {
    return {
      valid: false,
      reason: `Invalid TAN format: ${tan}. Expected: AAAA99999A`,
      flag: "INVALID_TAN_FORMAT",
      fraud_risk: "HIGH"
    };
  }

  const hash = seededRand(tan.toUpperCase() + (employerName || "").toLowerCase());
  const isActive = hash % 10 < 8; // 80% active
  const nameMatches = isActive && (hash % 10 < 7); // 70% name matches

  return {
    valid: true,
    tan: tan.toUpperCase(),
    source: "TRACES — TAN Verification",
    status: isActive ? "ACTIVE" : "DEACTIVATED",
    registered_deductor_name: nameMatches ? employerName : "Different Organisation",
    name_match: nameMatches,
    flag: !isActive ? "TAN_DEACTIVATED" : !nameMatches ? "TAN_EMPLOYER_NAME_MISMATCH" : null,
    fraud_risk: !isActive ? "HIGH" : !nameMatches ? "HIGH" : "LOW"
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// MASTER CROSS-REFERENCE FUNCTION
// ─────────────────────────────────────────────────────────────────────────────

/**
 * crossCheckSalaryWithITDept(salaryData, financialYear)
 * ─────────────────────────────────────────────────────────────────────────────
 * Cross-references claimed salary against BOTH Form 26AS and ITR.
 *
 * The Logic:
 *   Claimed Salary (salary slip) must be consistent with:
 *   1. Form 26AS TDS → reverse-calculated salary
 *   2. ITR declared income
 *   3. Employer TAN registration
 *
 * All three are GOVERNMENT RECORDS that the employee cannot alter.
 *
 * @param {Object} salaryData
 *   { pan, employer_tan, annual_income, monthly_tds_on_slip }
 * @param {string} financialYear
 */
function crossCheckSalaryWithITDept(salaryData, financialYear) {
  const { pan, employer_tan, annual_income, monthly_tds_on_slip } = salaryData;

  const result = {
    source: "Income Tax Department — Multi-Source Verification",
    claimed_annual_salary: annual_income,
    flags: [],
    tampering_detected: false,
    confidence: 100
  };

  // ── Check 1: Form 26AS ───────────────────────────────────────────────────
  if (pan) {
    const form26as = fetchForm26AS(pan, financialYear);
    result.form_26as = form26as;

    if (form26as.found && form26as.tds_records?.length > 0) {
      const itDerivedSalary = form26as.tds_records[0].it_derived_annual_salary;
      const salaryVariance = annual_income
        ? Math.abs(annual_income - itDerivedSalary) / itDerivedSalary
        : 0;

      if (annual_income && salaryVariance > 0.20) {
        result.tampering_detected = true;
        result.confidence -= 50;
        result.flags.push({
          flag: "FORM_26AS_SALARY_MISMATCH",
          severity: salaryVariance > 0.50 ? "CRITICAL" : "HIGH",
          claimed: annual_income,
          it_dept_record: itDerivedSalary,
          variance: (salaryVariance * 100).toFixed(1) + "%",
          implication: `IT Department's Form 26AS (based on employer's TDS filing) shows salary ~₹${itDerivedSalary.toLocaleString("en-IN")}/year. Salary slip claims ₹${annual_income?.toLocaleString("en-IN")}/year. ${salaryVariance > 0.5 ? "LIKELY TAMPERED." : "Significant discrepancy — needs manual review."}`
        });
      }

      // ── TDS on slip vs Form 26AS TDS ──────────────────────────────────────
      if (monthly_tds_on_slip && form26as.tds_records[0].monthly_tds) {
        const tdsVariance = Math.abs(monthly_tds_on_slip - form26as.tds_records[0].monthly_tds)
          / (form26as.tds_records[0].monthly_tds || 1);

        if (tdsVariance > 0.25) {
          result.tampering_detected = true;
          result.confidence -= 30;
          result.flags.push({
            flag: "TDS_AMOUNT_MISMATCH_WITH_26AS",
            severity: "HIGH",
            tds_on_slip: monthly_tds_on_slip,
            tds_in_26as: form26as.tds_records[0].monthly_tds,
            implication: "Monthly TDS deduction on salary slip does not match what employer actually deposited per Form 26AS. Suggests salary figure on slip was altered."
          });
        }
      }
    }
  }

  // ── Check 2: ITR Cross-Reference ─────────────────────────────────────────
  if (pan) {
    const itrData = fetchITRDetails(pan, financialYear);
    result.itr = itrData;

    if (itrData.found && annual_income) {
      const itrVariance = Math.abs(annual_income - itrData.declared_salary_income)
        / itrData.declared_salary_income;

      if (itrVariance > 0.20) {
        result.tampering_detected = true;
        result.confidence -= 40;
        result.flags.push({
          flag: "ITR_DECLARED_INCOME_MISMATCH",
          severity: itrVariance > 0.40 ? "CRITICAL" : "HIGH",
          claimed_on_slip: annual_income,
          declared_in_itr: itrData.declared_salary_income,
          variance: (itrVariance * 100).toFixed(1) + "%",
          implication: `Employee declared salary ₹${itrData.declared_salary_income.toLocaleString("en-IN")} in their own ITR filing (${itrData.financial_year}). Salary slip now claims ₹${annual_income.toLocaleString("en-IN")}. This contradiction suggests the slip has been altered for this application.`
        });
      }
    }
  }

  // ── Check 3: Employer TAN Verification ───────────────────────────────────
  if (employer_tan) {
    const tanResult = verifyEmployerTAN(employer_tan, salaryData.employer_name);
    result.tan_verification = tanResult;

    if (tanResult.flag) {
      result.flags.push({
        flag: tanResult.flag,
        severity: "HIGH",
        implication: tanResult.fraud_risk === "HIGH"
          ? "Employer TAN is invalid or belongs to a different organisation. Salary slip may be fabricated."
          : "Minor TAN issue — needs manual verification."
      });
      result.confidence -= tanResult.fraud_risk === "HIGH" ? 35 : 15;
    }
  }

  // ── Final Verdict ─────────────────────────────────────────────────────────
  result.confidence = Math.max(0, result.confidence);

  result.verdict = result.tampering_detected
    ? result.flags.some(f => f.severity === "CRITICAL")
      ? "REJECT — Strong evidence of salary slip tampering from multiple government sources."
      : "OFFICER_REVIEW — Discrepancies found between salary slip and government records."
    : "SALARY_CREDIBLE — Salary claim is consistent across government sources.";

  result.recommendation = result.tampering_detected
    ? (result.flags.some(f => f.severity === "CRITICAL") ? "REJECT" : "OFFICER_REVIEW")
    : "PROCEED";

  return result;
}

module.exports = {
  calculateExpectedTDS,
  fetchForm26AS,
  fetchITRDetails,
  verifyEmployerTAN,
  crossCheckSalaryWithITDept
};
